### ISSUE TITLE
This is great. Can we build a multilang tokenizer?

### ISSUE THREAD

**Issue by BlinkDL** [alasdairforsythe/tokenmonster#1]
Hi your work looks great. Is it doing greedy tokenization in the sense that always picking the longest possible token?

Here's my multilang greedy tokenization experiment FYI:
https://github.com/BlinkDL/ChatRWKV/blob/main/tokenizer/rwkv_tokenizer.py

**Comment by alasdairforsythe** [comment]
Yes, it's a greedy tokenizer. I'm implementing an ungreedy version atm.
For multilanguage, it will work out-of-the-box, I just need decent datasets.

**Comment by tiendung** [comment]
@alasdairforsythe I want to build token monster tknz for Vietnamese and English, and would like to ask can you provide me the English dataset you used to train token monster so I don't have download all (big) datasets and select portions from them. It will help me to concentrate on the Vietnamese part. Thank you very much.
