### ISSUE TITLE
Implemented in the new AI framework Zeta

### ISSUE THREAD

**Issue by kyegomez** [alasdairforsythe/tokenmonster#26]
Hey I like TokenMonster alot and have implemented it into our framework, Zeta, the framework enabling one to build the best multi-modality transformer models!

https://github.com/kyegomez/zeta

```
#!pip install zetascale

from zeta.tokenizers import TokenMonster
tokenizer = TokenMonster("englishcode-32000-consistent-v1")
tokens = tokenizer.tokenize("Hello world!")
print(tokens)

```

**Comment by alasdairforsythe** [comment]
Nice work!
