### ISSUE TITLE
Question/issue about uppercase

### ISSUE THREAD

**Issue by kerighan** [alasdairforsythe/tokenmonster#6]
I'm currently training a language model with your tokenizer. I have to say that preliminary results are amazing and am very impressed.

I have a question though: how is uppercase handled by the tokenizer? It's maybe a side effect of the tokenizer, but my current model seems to produce a lot of fully uppercased texts (90% of the time), even though the training data does not contain that much uppercased text. What's strange is that the produced text is very coherent and likely comes from lowercased training data. I suspect that uppercase is some kind of state that can be switched on and off in your tokenizer and that the model does not learn to switch it off (EDIT: this is very likely, as my model is able to code html in uppercase). Another hypothesis is an error in your code.

I'm training on Eleuther's Pile in a way that I'm very familiar, and only the tokenizer changed, so it's not an error from this side of things.

**Comment by alasdairforsythe** [comment]
Yeah, that'll be from capcode. It uses "B" (begin) and "E" (end) tokens to mark sequences of capitals of 3 or more words in a row. I can see how that could lead to the behavior you're describing.

I'm currently making some modification to capcode to implement a "delete" token. I'll remove the B and E tokens only use single word modifiers, which will stop that behavior.

In the meantime you can use one of the vocabularies without capcode.
