### ISSUE TITLE
Tokenize strings of only N-types of characters?

### ISSUE THREAD

**Issue by ianderrington** [alasdairforsythe/tokenmonster#8]
Hi, I'm looking at this for tokenizing biological sequences: protein, DNA, RNA. These have between 4-22 letters, generally. When I use the procedure, it only finds the base-letters as tokens. The vocabulary that is produced  consists of the base ascii characters 
`less vocab.txt`
```
^A
^B
^C
^D
^E
^F
^G
^H



^K
^L
^M
^N
^O
^P
^Q
^R
^S
^T
^U
^V
^W
^X
^Y
^Z
^[
^\
^]
^^
^_

!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
0
1
2
3
4
5
6
7
8
9
:
;
<
=
>
?
@
A
B
C
D
...
```
Even though none of those characters, except for ACGT were in the input text. The code I entered was this:

```
./getalltokens -charset utf8 -chunk-size 10000 -dataset my_data.txt -min-occur-chunk 2 -output vocab.vc -workers 2
./trainvocab -charset utf-8 -dataset my_data.txt -dir vocab_dir -dictionary vocab.vc -max-token-length 64 -vocab 4095
./exporttokens ./vocab_dir/794556_5737.zlib vocab -capcode -charset UTF-8 -txt
```

Can you advise?

**Comment by alasdairforsythe** [comment]
Yes, there is a parameter during training that adds all base characters, which you need to disable.

For your purpose you want to ensure you use charset "binary". With getalltokens there is a parameter for -include-single-bytes, set that to false. Then on trainvocab you need to set the -no-reserve-256 flag.

**Comment by ianderrington** [comment]
Thanks for the help! Would you have a buy-me-a-coffee? I always appreciate those dealing with my silly mistakes.

**Comment by ianderrington** [comment]
It worked very well. Thank you again!
